#
# Configurations
#
CONFIG_UNISOC_JPG := m

#
# Source List
#
jpg-y := \
	sprd_jpg.o\
	sprd_jpg_common.o

#
# Build Options
#

#
# Final Objects
#
obj-$(CONFIG_UNISOC_JPG) := jpg.o
KO_MODULE_PATH := $(src)
EXTRA_CFLAGS += -I$(KO_MODULE_PATH)/../../../common/camera/power/kernel/