#
# flash_ic_ocp8137.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := flash_ic_ocp8137
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)
PROTECT_DIR:=$(BSP_BOARD_CAMERA_PRODECT_NAME)

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)/../flash_drv
ifneq ($(findstring $(strip $(PROTECT_DIR)), ums9230_hulk),)
    ccflags-y += -I$(KO_MODULE_PATH)/../../$(PROTECT_DIR)/interface
else
    ccflags-y += -I$(KO_MODULE_PATH)/../../interface
endif

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
