#
# Configurations
#
CONFIG_UNISOC_VSP := m

#
# Source List
#
vsp-y := \
	sprd_vsp.o \
	vsp_common.o \
	vsp_isr_func.o

#
# Build Options
#
#
# Final Objects
#
obj-$(CONFIG_UNISOC_VSP) := vsp.o
KO_MODULE_PATH := $(src)
EXTRA_CFLAGS += -I$(KO_MODULE_PATH)/../../../common/camera/power/kernel/
