#
# snd-soc-sprd-card.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd-soc-sprd-card
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

ccflags-y += -I$(KO_MODULE_PATH)/../../include
ccflags-y += -I$(KO_MODULE_PATH)/../../codec/sprd
ccflags-y += -I$(KO_MODULE_PATH)/../../../sprd_audio/agdsp_access
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_sharkl3_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKL3
endif
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_pike2_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_PIKE2
endif
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_sharkle_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2721
ccflags-y += -DCONFIG_SND_SOC_UNISOC_SHARKLE
endif
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_sharkl5Pro_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2730
endif
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_sharkl5_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2730
endif
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_qogirl6_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_SC2730
endif
ifeq ($(BSP_KERNEL_DEFCONFIG),sprd_qogirn6pro_defconfig)
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
endif

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/*.c)

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o

SPRD_CARD_COMMON := \
		vbc-rxpx-codec-sc27xx.o \
		sprd-asoc-common.o \
		sprd-asoc-card-utils.o

ifeq ($(BSP_BOARD_AUDIO_EXTPA),true)
SPRD_CARD := \
		sprd-asoc-card-utils-hook_14c10.o \
		sprd-asoc-card-utils-legacy_14c10.o
else
SPRD_CARD := \
		sprd-asoc-card-utils-hook.o \
		sprd-asoc-card-utils-legacy.o
endif

$(KO_MODULE_NAME)-y += \
		$(SPRD_CARD_COMMON) \
		$(SPRD_CARD)

# Comment it if the only object file has the same name with module
# $(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
